name: Test Github Workflows

on:
  push:
    branches: [master]

jobs:
  info:
    name: Get Information
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Webhook JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ${GITHUB_EVENT_PATH}
          echo
          PR_NUMBER="$(cat ${GITHUB_EVENT_PATH} | jq -r .head_commit.message |grep '#' |perl -pe 's/.*#(\d+).*/\1/')"
          PR_NAME="$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER} |jq -r .title)"
          WHO_DID_IT="$(cat ${GITHUB_EVENT_PATH} |jq -r .head_commit.author.name) ($(cat ${GITHUB_EVENT_PATH} |jq -r .head_commit.author.username))"
          #PR_NAME="$(cat ${GITHUB_EVENT_PATH} |jq -r .head_commit.message |tail -1)"
          echo "${PR_NAME} -- ${WHO_DID_IT}"
